### ISSUE TITLE
Incorrect instructions

### ISSUE THREAD

**Issue by randeenapp** [MicrosoftDocs/dynamics-365-project-operations#75]
The "Action Pane" and "Feature Control tab" do not exist for resource/non-stock Settings.

"To turn on the ability to activate and revise project-based quotes, follow these steps.

Go to Settings > Parameters.
Open the Parameters record.
On the Action Pane, on the Feature Control tab, select Enable activation and revision of quotes."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 533d59ab-eb71-0a15-69dc-92316df5ea8c
* Version Independent ID: 533d59ab-eb71-0a15-69dc-92316df5ea8c
* Content: [Activate and revise a project quote](https://learn.microsoft.com/en-us/dynamics365/project-operations/sales/activation-and-revision)
* Content Source: [articles/sales/activation-and-revision.md](https://github.com/MicrosoftDocs/dynamics-365-project-operations/blob/main/articles/sales/activation-and-revision.md)
* Service: **dynamics-365-project-operations**
* GitHub Login: @rumant
* Microsoft Alias: **rumant**

**Comment by rumant** [comment]
Yes they do exist. Here's a screen capture. On this I already enabled revision and acitvation of quotes so you no longer see it. But this would be location where you would find it on an org where you have not enabled this feature yet.

[cid:a7a96995-3681-449a-b2d0-e9760d864194]

Thanks,
Rupa


Our workplace allows for a flexible work schedule. I am sending this email now because it is convenient for me. I do not expect you to read or respond to this email until it is convenient for you.


________________________________
From: randeenapp ***@***.***>
Sent: Wednesday, January 18, 2023 9:46 AM
To: MicrosoftDocs/dynamics-365-project-operations ***@***.***>
Cc: Rupa Mantravadi ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/dynamics-365-project-operations] Incorrect instructions (Issue #75)


The "Action Pane" and "Feature Control tab" do not exist for resource/non-stock Settings.

"To turn on the ability to activate and revise project-based quotes, follow these steps.

Go to Settings > Parameters.
Open the Parameters record.
On the Action Pane, on the Feature Control tab, select Enable activation and revision of quotes."

________________________________
Document Details

⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

  *   ID: 533d59ab-eb71-0a15-69dc-92316df5ea8c
  *   Version Independent ID: 533d59ab-eb71-0a15-69dc-92316df5ea8c
  *   Content: Activate and revise a project quote<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdynamics365%2Fproject-operations%2Fsales%2Factivation-and-revision&data=05%7C01%7Crumant%40microsoft.com%7Ce1d56a36e02847b966bb08daf97befb9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638096607954682149%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SDStmYjH0uZ5flyvRBpL1iQSfOdsgubk0yRMavgMKFU%3D&reserved=0>
  *   Content Source: articles/sales/activation-and-revision.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fdynamics-365-project-operations%2Fblob%2Fmain%2Farticles%2Fsales%2Factivation-and-revision.md&data=05%7C01%7Crumant%40microsoft.com%7Ce1d56a36e02847b966bb08daf97befb9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638096607954682149%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3qkvN95XAgY4i3lIoyYXDt%2B7M8S%2FPtCO1K%2Fht6HcPZM%3D&reserved=0>
  *   Service: dynamics-365-project-operations
  *   GitHub Login: @rumant<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frumant&data=05%7C01%7Crumant%40microsoft.com%7Ce1d56a36e02847b966bb08daf97befb9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638096607954682149%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hQEFs%2FfewTtpvElcRUEZSzFNeMzBdA1SMsfD7Q6VKZs%3D&reserved=0>
  *   Microsoft Alias: rumant

**Comment by randeenapp** [comment]
Hi, there was no screenshot that was viewable. If I understand correctly, the dependency (which wasn't referenced) is having revision and activation of quotes enabled or disabled?

Thank you!

**Comment by rumant** [comment]
If you have not enabled it already, you should see the button in the dropdown of the Feature control button at the top of the page. Once you enable it, the button is removed from the Feature control menu.

Thanks,
Rupa


Our workplace allows for a flexible work schedule. I am sending this email now because it is convenient for me. I do not expect you to read or respond to this email until it is convenient for you.

________________________________

**Comment by rumant** [comment]
![image](https://user-images.githubusercontent.com/39802685/214908255-ca1e7353-714f-4860-807c-b76babc744a4.png)
