### ISSUE TITLE
Project budget forecast article line 61 is missing information

### ISSUE THREAD

**Issue by anttipajunen** [MicrosoftDocs/dynamics-365-project-operations#80]
Sentence on line 61 is missing words and ins incomplete.

https://github.com/MicrosoftDocs/dynamics-365-project-operations/blob/main/articles/pro/budget/keyconcepts-projectbudget.md#budget-forecast

![image](https://user-images.githubusercontent.com/64043240/216811472-8b5ddb0e-f1cc-43ce-8386-10aae1f066e0.png)

**Comment by johnmichalak** [comment]
@niranjanmaski Can you take a look at this to see if changes should be made? Perhaps we could change to: If actual costs are more than the forecasted cost for a budget line, the forecast cost will be made equal to the actual cost.

**Comment by johnmichalak** [comment]
@niranjanmaski for the second sentence, This is due to the fact that actuals already have ________ than the budget, the forecast will be at least equal to the actuals.

**Comment by niranjanmaski** [comment]
I agree @johnmichalak we can change this. 'more' is the missing word. 

"If actual costs are more than the forecasted cost for a budget line, the forecast cost will be made equal to the actual cost. This is due to the fact that actuals already have more than budget, the forecast will be at least equal to the actuals."
